name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      # 1 Checkout code
      - uses: actions/checkout@v4

      # 2 Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # 3 Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4 Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # 5 Ensure output folder exists
      - name: Ensure results folder exists
        run: mkdir -p results/full

      # 6 Run all tests with HTML report
      - name: Run All Playwright Tests
        run: |
          npx playwright test --reporter=html --output=results/full
      # 7️⃣ Upload HTML report as artifact
      - name: Upload Playwright HTML Report
        uses: actions/upload-artifact@v4
        with:
         name: playwright-html-report
         path: results/full
         retention-days: 30
    
